# automated migration configuration file

# description of the attributes:
# 'files_to_migrate' contains paths to files in the data repo to migrate
# 'schema_repo_url' contains the URL of the schema repo
# 'schema_file' contains the relative path to the schema file in the schema repo
# 'migrator' contains the keyword for the type of migrator to use, a key in `MigrationSpec.MIGRATOR_CREATOR_MAP`
files_to_migrate:
- ../examples/transcription_translation_hybrid_model/model_9c7dbdc.xlsx
migrator: wc_lang
schema_file: ../wc_lang/core.py
schema_repo_url: https://github.com/KarrLab/wc_lang
