name: docs
channels:
  - conda-forge
  - defaults
  - SBMLTeam
  - sys-bio
dependencies:
  - libsedml
  - matplotlib
  - numpy
  - pip
  - python
  - python-libsbml
  - scipy
  - sphinx
  - pip:
    - configparser
    - robpol86_sphinxcontrib_googleanalytics
    - six
    - sphinx_rtd_theme
    - sphinxcontrib_bibtex
    - sphinxcontrib_spelling
